version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: maxjazz/foodgram
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.5-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/
      - ./media:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - web
    env_file:
      - ./.env
