# Generated by Django 3.0.8 on 2021-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_auto_20210210_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ингредиента'),
        ),
    ]
